---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: names
spec:
  selector:
    matchLabels:
      app: names
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: names
        tier: frontend
    spec:
      containers:
        - name: names
          image: docker.io/library/names:0.0.1-SNAPSHOT
          env:
          - name: UPPERCASE_ENDPOINT
            value: "http://uppercase:8081/uppercase"

